// Auto-generated by `supabase gen types typescript` (via Supabase MCP).
// Do not edit by hand. Re-generate after every migration.
// Last generated: 2026-04-29 (Sprint B1, after migrations 0011 + 0012).

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      award_allowances: {
        Row: {
          amount: number
          award_id: string
          code: string
          created_at: string
          description: string
          effective_from: string
          effective_to: string | null
          fwc_clause: string
          id: string
          purpose: string
          unit: string
        }
        Insert: {
          amount: number
          award_id: string
          code: string
          created_at?: string
          description: string
          effective_from: string
          effective_to?: string | null
          fwc_clause: string
          id?: string
          purpose?: string
          unit: string
        }
        Update: {
          amount?: number
          award_id?: string
          code?: string
          created_at?: string
          description?: string
          effective_from?: string
          effective_to?: string | null
          fwc_clause?: string
          id?: string
          purpose?: string
          unit?: string
        }
        Relationships: [
          {
            foreignKeyName: "award_allowances_award_id_fkey"
            columns: ["award_id"]
            isOneToOne: false
            referencedRelation: "awards"
            referencedColumns: ["id"]
          },
        ]
      }
      award_rates: {
        Row: {
          amount: number
          award_id: string
          classification_code: string
          effective_from: string
          effective_to: string | null
          id: string
          pay_basis: string
        }
        Insert: {
          amount: number
          award_id: string
          classification_code: string
          effective_from: string
          effective_to?: string | null
          id?: string
          pay_basis: string
        }
        Update: {
          amount?: number
          award_id?: string
          classification_code?: string
          effective_from?: string
          effective_to?: string | null
          id?: string
          pay_basis?: string
        }
        Relationships: [
          {
            foreignKeyName: "award_rates_award_id_fkey"
            columns: ["award_id"]
            isOneToOne: false
            referencedRelation: "awards"
            referencedColumns: ["id"]
          },
        ]
      }
      awards: {
        Row: {
          award_code: string
          effective_from: string | null
          effective_to: string | null
          fwc_consolidation_date: string | null
          fwc_source_url: string | null
          id: string
          title: string
        }
        Insert: {
          award_code: string
          effective_from?: string | null
          effective_to?: string | null
          fwc_consolidation_date?: string | null
          fwc_source_url?: string | null
          id?: string
          title: string
        }
        Update: {
          award_code?: string
          effective_from?: string | null
          effective_to?: string | null
          fwc_consolidation_date?: string | null
          fwc_source_url?: string | null
          id?: string
          title?: string
        }
        Relationships: []
      }
      bank_deposit_facts: {
        Row: {
          amount: number | null
          confirmed_at: string | null
          created_at: string
          deposited_at: string | null
          id: string
          narration: string | null
          provenance: string
          source_doc_id: string | null
          updated_at: string
          worker_id: string
        }
        Insert: {
          amount?: number | null
          confirmed_at?: string | null
          created_at?: string
          deposited_at?: string | null
          id?: string
          narration?: string | null
          provenance: string
          source_doc_id?: string | null
          updated_at?: string
          worker_id: string
        }
        Update: {
          amount?: number | null
          confirmed_at?: string | null
          created_at?: string
          deposited_at?: string | null
          id?: string
          narration?: string | null
          provenance?: string
          source_doc_id?: string | null
          updated_at?: string
          worker_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "bank_deposit_facts_source_doc_id_fkey"
            columns: ["source_doc_id"]
            isOneToOne: false
            referencedRelation: "documents"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "bank_deposit_facts_worker_id_fkey"
            columns: ["worker_id"]
            isOneToOne: false
            referencedRelation: "workers"
            referencedColumns: ["id"]
          },
        ]
      }
      bank_deposit_facts_history: {
        Row: {
          amount: number | null
          change_type: string
          changed_at: string
          confirmed_at: string | null
          deposited_at: string | null
          fact_id: string
          id: string
          narration: string | null
          provenance: string
          source_doc_id: string | null
          worker_id: string
        }
        Insert: {
          amount?: number | null
          change_type: string
          changed_at?: string
          confirmed_at?: string | null
          deposited_at?: string | null
          fact_id: string
          id?: string
          narration?: string | null
          provenance: string
          source_doc_id?: string | null
          worker_id: string
        }
        Update: {
          amount?: number | null
          change_type?: string
          changed_at?: string
          confirmed_at?: string | null
          deposited_at?: string | null
          fact_id?: string
          id?: string
          narration?: string | null
          provenance?: string
          source_doc_id?: string | null
          worker_id?: string
        }
        Relationships: []
      }
      comparisons: {
        Row: {
          award_ref_snapshot: Json
          created_at: string
          expected_amounts: Json
          gap: Json
          id: string
          inputs_snapshot: Json
          period_end: string
          period_start: string
          received_amounts: Json
          report_pdf_storage_path: string | null
          worker_id: string
        }
        Insert: {
          award_ref_snapshot: Json
          created_at?: string
          expected_amounts: Json
          gap: Json
          id?: string
          inputs_snapshot: Json
          period_end: string
          period_start: string
          received_amounts: Json
          report_pdf_storage_path?: string | null
          worker_id: string
        }
        Update: {
          award_ref_snapshot?: Json
          created_at?: string
          expected_amounts?: Json
          gap?: Json
          id?: string
          inputs_snapshot?: Json
          period_end?: string
          period_start?: string
          received_amounts?: Json
          report_pdf_storage_path?: string | null
          worker_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "comparisons_worker_id_fkey"
            columns: ["worker_id"]
            isOneToOne: false
            referencedRelation: "workers"
            referencedColumns: ["id"]
          },
        ]
      }
      consent_records: {
        Row: {
          consented_at: string
          id: string
          ip_address: unknown
          privacy_policy_version: string
          user_agent: string | null
          worker_id: string
        }
        Insert: {
          consented_at?: string
          id?: string
          ip_address?: unknown
          privacy_policy_version: string
          user_agent?: string | null
          worker_id: string
        }
        Update: {
          consented_at?: string
          id?: string
          ip_address?: unknown
          privacy_policy_version?: string
          user_agent?: string | null
          worker_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "consent_records_worker_id_fkey"
            columns: ["worker_id"]
            isOneToOne: false
            referencedRelation: "workers"
            referencedColumns: ["id"]
          },
        ]
      }
      document_classifications: {
        Row: {
          classified_at: string
          classifier_version: string
          confidence: number | null
          created_at: string
          detected_type: string | null
          document_id: string
          id: string
          notes: string | null
          page_range: unknown
          parent_doc_id: string | null
          routing_status: string | null
          updated_at: string
        }
        Insert: {
          classified_at?: string
          classifier_version: string
          confidence?: number | null
          created_at?: string
          detected_type?: string | null
          document_id: string
          id?: string
          notes?: string | null
          page_range?: unknown
          parent_doc_id?: string | null
          routing_status?: string | null
          updated_at?: string
        }
        Update: {
          classified_at?: string
          classifier_version?: string
          confidence?: number | null
          created_at?: string
          detected_type?: string | null
          document_id?: string
          id?: string
          notes?: string | null
          page_range?: unknown
          parent_doc_id?: string | null
          routing_status?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "document_classifications_document_id_fkey"
            columns: ["document_id"]
            isOneToOne: false
            referencedRelation: "documents"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "document_classifications_parent_doc_id_fkey"
            columns: ["parent_doc_id"]
            isOneToOne: false
            referencedRelation: "documents"
            referencedColumns: ["id"]
          },
        ]
      }
      document_extractions: {
        Row: {
          bucket: string
          created_at: string
          document_id: string
          extracted_at: string
          extracted_jsonb: Json | null
          extraction_status: string
          extractor_version: string
          field_confidences: Json | null
          id: string
          updated_at: string
        }
        Insert: {
          bucket: string
          created_at?: string
          document_id: string
          extracted_at?: string
          extracted_jsonb?: Json | null
          extraction_status: string
          extractor_version: string
          field_confidences?: Json | null
          id?: string
          updated_at?: string
        }
        Update: {
          bucket?: string
          created_at?: string
          document_id?: string
          extracted_at?: string
          extracted_jsonb?: Json | null
          extraction_status?: string
          extractor_version?: string
          field_confidences?: Json | null
          id?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "document_extractions_document_id_fkey"
            columns: ["document_id"]
            isOneToOne: false
            referencedRelation: "documents"
            referencedColumns: ["id"]
          },
        ]
      }
      documents: {
        Row: {
          archived_at: string | null
          batch_id: string | null
          content_hash: string | null
          deleted_at: string | null
          doc_type: string
          embedding: string | null
          id: string
          mime_type: string | null
          original_filename: string | null
          size_bytes: number | null
          state: string
          storage_path: string
          uploaded_at: string
          worker_facing_name: string | null
          worker_id: string
        }
        Insert: {
          archived_at?: string | null
          batch_id?: string | null
          content_hash?: string | null
          deleted_at?: string | null
          doc_type: string
          embedding?: string | null
          id?: string
          mime_type?: string | null
          original_filename?: string | null
          size_bytes?: number | null
          state?: string
          storage_path: string
          uploaded_at?: string
          worker_facing_name?: string | null
          worker_id: string
        }
        Update: {
          archived_at?: string | null
          batch_id?: string | null
          content_hash?: string | null
          deleted_at?: string | null
          doc_type?: string
          embedding?: string | null
          id?: string
          mime_type?: string | null
          original_filename?: string | null
          size_bytes?: number | null
          state?: string
          storage_path?: string
          uploaded_at?: string
          worker_facing_name?: string | null
          worker_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "documents_worker_id_fkey"
            columns: ["worker_id"]
            isOneToOne: false
            referencedRelation: "workers"
            referencedColumns: ["id"]
          },
        ]
      }
      employer_extraction_patterns: {
        Row: {
          archived_at: string | null
          confidence: number | null
          created_at: string
          document_type: string
          employer_id: string
          id: string
          last_observed: string
          observation_count: number
          pattern_jsonb: Json
          updated_at: string
        }
        Insert: {
          archived_at?: string | null
          confidence?: number | null
          created_at?: string
          document_type: string
          employer_id: string
          id?: string
          last_observed?: string
          observation_count?: number
          pattern_jsonb: Json
          updated_at?: string
        }
        Update: {
          archived_at?: string | null
          confidence?: number | null
          created_at?: string
          document_type?: string
          employer_id?: string
          id?: string
          last_observed?: string
          observation_count?: number
          pattern_jsonb?: Json
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "employer_extraction_patterns_employer_id_fkey"
            columns: ["employer_id"]
            isOneToOne: false
            referencedRelation: "employers"
            referencedColumns: ["id"]
          },
        ]
      }
      employers: {
        Row: {
          abn: string | null
          created_at: string
          id: string
          legal_name: string
          updated_at: string
        }
        Insert: {
          abn?: string | null
          created_at?: string
          id?: string
          legal_name: string
          updated_at?: string
        }
        Update: {
          abn?: string | null
          created_at?: string
          id?: string
          legal_name?: string
          updated_at?: string
        }
        Relationships: []
      }
      payslip_facts: {
        Row: {
          allowances: Json | null
          confirmed_at: string | null
          created_at: string
          deductions: Json | null
          employer_id: string
          gross_pay: number | null
          id: string
          net_pay: number | null
          ordinary_hours: number | null
          ordinary_rate: number | null
          ot_hours: number | null
          ot_rate: number | null
          period_end: string | null
          period_start: string | null
          provenance: string
          source_doc_id: string | null
          super_amount: number | null
          super_destination: string | null
          tax: number | null
          updated_at: string
          worker_id: string
        }
        Insert: {
          allowances?: Json | null
          confirmed_at?: string | null
          created_at?: string
          deductions?: Json | null
          employer_id: string
          gross_pay?: number | null
          id?: string
          net_pay?: number | null
          ordinary_hours?: number | null
          ordinary_rate?: number | null
          ot_hours?: number | null
          ot_rate?: number | null
          period_end?: string | null
          period_start?: string | null
          provenance: string
          source_doc_id?: string | null
          super_amount?: number | null
          super_destination?: string | null
          tax?: number | null
          updated_at?: string
          worker_id: string
        }
        Update: {
          allowances?: Json | null
          confirmed_at?: string | null
          created_at?: string
          deductions?: Json | null
          employer_id?: string
          gross_pay?: number | null
          id?: string
          net_pay?: number | null
          ordinary_hours?: number | null
          ordinary_rate?: number | null
          ot_hours?: number | null
          ot_rate?: number | null
          period_end?: string | null
          period_start?: string | null
          provenance?: string
          source_doc_id?: string | null
          super_amount?: number | null
          super_destination?: string | null
          tax?: number | null
          updated_at?: string
          worker_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "payslip_facts_employer_id_fkey"
            columns: ["employer_id"]
            isOneToOne: false
            referencedRelation: "employers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "payslip_facts_source_doc_id_fkey"
            columns: ["source_doc_id"]
            isOneToOne: false
            referencedRelation: "documents"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "payslip_facts_worker_id_fkey"
            columns: ["worker_id"]
            isOneToOne: false
            referencedRelation: "workers"
            referencedColumns: ["id"]
          },
        ]
      }
      payslip_facts_history: {
        Row: {
          allowances: Json | null
          change_type: string
          changed_at: string
          confirmed_at: string | null
          deductions: Json | null
          employer_id: string
          fact_id: string
          gross_pay: number | null
          id: string
          net_pay: number | null
          ordinary_hours: number | null
          ordinary_rate: number | null
          ot_hours: number | null
          ot_rate: number | null
          period_end: string | null
          period_start: string | null
          provenance: string
          source_doc_id: string | null
          super_amount: number | null
          super_destination: string | null
          tax: number | null
          worker_id: string
        }
        Insert: {
          allowances?: Json | null
          change_type: string
          changed_at?: string
          confirmed_at?: string | null
          deductions?: Json | null
          employer_id: string
          fact_id: string
          gross_pay?: number | null
          id?: string
          net_pay?: number | null
          ordinary_hours?: number | null
          ordinary_rate?: number | null
          ot_hours?: number | null
          ot_rate?: number | null
          period_end?: string | null
          period_start?: string | null
          provenance: string
          source_doc_id?: string | null
          super_amount?: number | null
          super_destination?: string | null
          tax?: number | null
          worker_id: string
        }
        Update: {
          allowances?: Json | null
          change_type?: string
          changed_at?: string
          confirmed_at?: string | null
          deductions?: Json | null
          employer_id?: string
          fact_id?: string
          gross_pay?: number | null
          id?: string
          net_pay?: number | null
          ordinary_hours?: number | null
          ordinary_rate?: number | null
          ot_hours?: number | null
          ot_rate?: number | null
          period_end?: string | null
          period_start?: string | null
          provenance?: string
          source_doc_id?: string | null
          super_amount?: number | null
          super_destination?: string | null
          tax?: number | null
          worker_id?: string
        }
        Relationships: []
      }
      shift_facts: {
        Row: {
          break_minutes: number
          confirmed_at: string | null
          created_at: string
          employer_id: string
          ended_at: string | null
          id: string
          notes: string | null
          provenance: string
          shift_type: string | null
          source_doc_id: string | null
          started_at: string | null
          updated_at: string
          worker_id: string
        }
        Insert: {
          break_minutes?: number
          confirmed_at?: string | null
          created_at?: string
          employer_id: string
          ended_at?: string | null
          id?: string
          notes?: string | null
          provenance: string
          shift_type?: string | null
          source_doc_id?: string | null
          started_at?: string | null
          updated_at?: string
          worker_id: string
        }
        Update: {
          break_minutes?: number
          confirmed_at?: string | null
          created_at?: string
          employer_id?: string
          ended_at?: string | null
          id?: string
          notes?: string | null
          provenance?: string
          shift_type?: string | null
          source_doc_id?: string | null
          started_at?: string | null
          updated_at?: string
          worker_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "shift_facts_employer_id_fkey"
            columns: ["employer_id"]
            isOneToOne: false
            referencedRelation: "employers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "shift_facts_source_doc_id_fkey"
            columns: ["source_doc_id"]
            isOneToOne: false
            referencedRelation: "documents"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "shift_facts_worker_id_fkey"
            columns: ["worker_id"]
            isOneToOne: false
            referencedRelation: "workers"
            referencedColumns: ["id"]
          },
        ]
      }
      shift_facts_history: {
        Row: {
          break_minutes: number
          change_type: string
          changed_at: string
          confirmed_at: string | null
          employer_id: string
          ended_at: string | null
          fact_id: string
          id: string
          notes: string | null
          provenance: string
          shift_type: string | null
          source_doc_id: string | null
          started_at: string | null
          worker_id: string
        }
        Insert: {
          break_minutes: number
          change_type: string
          changed_at?: string
          confirmed_at?: string | null
          employer_id: string
          ended_at?: string | null
          fact_id: string
          id?: string
          notes?: string | null
          provenance: string
          shift_type?: string | null
          source_doc_id?: string | null
          started_at?: string | null
          worker_id: string
        }
        Update: {
          break_minutes?: number
          change_type?: string
          changed_at?: string
          confirmed_at?: string | null
          employer_id?: string
          ended_at?: string | null
          fact_id?: string
          id?: string
          notes?: string | null
          provenance?: string
          shift_type?: string | null
          source_doc_id?: string | null
          started_at?: string | null
          worker_id?: string
        }
        Relationships: []
      }
      super_contribution_facts: {
        Row: {
          amount: number | null
          confirmed_at: string | null
          created_at: string
          id: string
          provenance: string
          received_at: string | null
          source_doc_id: string | null
          source_employer: string | null
          updated_at: string
          worker_id: string
        }
        Insert: {
          amount?: number | null
          confirmed_at?: string | null
          created_at?: string
          id?: string
          provenance: string
          received_at?: string | null
          source_doc_id?: string | null
          source_employer?: string | null
          updated_at?: string
          worker_id: string
        }
        Update: {
          amount?: number | null
          confirmed_at?: string | null
          created_at?: string
          id?: string
          provenance?: string
          received_at?: string | null
          source_doc_id?: string | null
          source_employer?: string | null
          updated_at?: string
          worker_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "super_contribution_facts_source_doc_id_fkey"
            columns: ["source_doc_id"]
            isOneToOne: false
            referencedRelation: "documents"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "super_contribution_facts_worker_id_fkey"
            columns: ["worker_id"]
            isOneToOne: false
            referencedRelation: "workers"
            referencedColumns: ["id"]
          },
        ]
      }
      super_contribution_facts_history: {
        Row: {
          amount: number | null
          change_type: string
          changed_at: string
          confirmed_at: string | null
          fact_id: string
          id: string
          provenance: string
          received_at: string | null
          source_doc_id: string | null
          source_employer: string | null
          worker_id: string
        }
        Insert: {
          amount?: number | null
          change_type: string
          changed_at?: string
          confirmed_at?: string | null
          fact_id: string
          id?: string
          provenance: string
          received_at?: string | null
          source_doc_id?: string | null
          source_employer?: string | null
          worker_id: string
        }
        Update: {
          amount?: number | null
          change_type?: string
          changed_at?: string
          confirmed_at?: string | null
          fact_id?: string
          id?: string
          provenance?: string
          received_at?: string | null
          source_doc_id?: string | null
          source_employer?: string | null
          worker_id?: string
        }
        Relationships: []
      }
      worker_classification_facts: {
        Row: {
          award_id: string | null
          classification_code: string | null
          confirmed_at: string | null
          created_at: string
          effective_from: string | null
          effective_to: string | null
          employer_id: string
          id: string
          provenance: string
          source_doc_id: string | null
          updated_at: string
          worker_id: string
        }
        Insert: {
          award_id?: string | null
          classification_code?: string | null
          confirmed_at?: string | null
          created_at?: string
          effective_from?: string | null
          effective_to?: string | null
          employer_id: string
          id?: string
          provenance: string
          source_doc_id?: string | null
          updated_at?: string
          worker_id: string
        }
        Update: {
          award_id?: string | null
          classification_code?: string | null
          confirmed_at?: string | null
          created_at?: string
          effective_from?: string | null
          effective_to?: string | null
          employer_id?: string
          id?: string
          provenance?: string
          source_doc_id?: string | null
          updated_at?: string
          worker_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "worker_classification_facts_award_id_fkey"
            columns: ["award_id"]
            isOneToOne: false
            referencedRelation: "awards"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "worker_classification_facts_employer_id_fkey"
            columns: ["employer_id"]
            isOneToOne: false
            referencedRelation: "employers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "worker_classification_facts_source_doc_id_fkey"
            columns: ["source_doc_id"]
            isOneToOne: false
            referencedRelation: "documents"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "worker_classification_facts_worker_id_fkey"
            columns: ["worker_id"]
            isOneToOne: false
            referencedRelation: "workers"
            referencedColumns: ["id"]
          },
        ]
      }
      worker_classification_facts_history: {
        Row: {
          award_id: string | null
          change_type: string
          changed_at: string
          classification_code: string | null
          confirmed_at: string | null
          effective_from: string | null
          effective_to: string | null
          employer_id: string
          fact_id: string
          id: string
          provenance: string
          source_doc_id: string | null
          worker_id: string
        }
        Insert: {
          award_id?: string | null
          change_type: string
          changed_at?: string
          classification_code?: string | null
          confirmed_at?: string | null
          effective_from?: string | null
          effective_to?: string | null
          employer_id: string
          fact_id: string
          id?: string
          provenance: string
          source_doc_id?: string | null
          worker_id: string
        }
        Update: {
          award_id?: string | null
          change_type?: string
          changed_at?: string
          classification_code?: string | null
          confirmed_at?: string | null
          effective_from?: string | null
          effective_to?: string | null
          employer_id?: string
          fact_id?: string
          id?: string
          provenance?: string
          source_doc_id?: string | null
          worker_id?: string
        }
        Relationships: []
      }
      worker_extraction_preferences: {
        Row: {
          archived_at: string | null
          confidence: number | null
          created_at: string
          id: string
          last_observed: string
          observation_count: number
          preference_key: string
          preference_value: Json
          updated_at: string
          worker_id: string
        }
        Insert: {
          archived_at?: string | null
          confidence?: number | null
          created_at?: string
          id?: string
          last_observed?: string
          observation_count?: number
          preference_key: string
          preference_value: Json
          updated_at?: string
          worker_id: string
        }
        Update: {
          archived_at?: string | null
          confidence?: number | null
          created_at?: string
          id?: string
          last_observed?: string
          observation_count?: number
          preference_key?: string
          preference_value?: Json
          updated_at?: string
          worker_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "worker_extraction_preferences_worker_id_fkey"
            columns: ["worker_id"]
            isOneToOne: false
            referencedRelation: "workers"
            referencedColumns: ["id"]
          },
        ]
      }
      workers: {
        Row: {
          clerk_user_id: string
          country: string | null
          created_at: string
          display_name: string | null
          id: string
          preferred_language: string
          tier: string
          updated_at: string
        }
        Insert: {
          clerk_user_id: string
          country?: string | null
          created_at?: string
          display_name?: string | null
          id?: string
          preferred_language?: string
          tier?: string
          updated_at?: string
        }
        Update: {
          clerk_user_id?: string
          country?: string | null
          created_at?: string
          display_name?: string | null
          id?: string
          preferred_language?: string
          tier?: string
          updated_at?: string
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      current_worker_id: { Args: never; Returns: string }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

